### ISSUE TITLE
usage of archived TF provider

### ISSUE THREAD

**Issue by n0npax** [GoogleCloudPlatform/dlp-pdf-redaction#13]
As per: https://registry.terraform.io/providers/hashicorp/template/latest

> This provider has been archived. Please use the `templatefile` function or the `Cloudinit` provider instead. See documentation for more details.

Solution can't be deployed from m1 Mac as archived provider doesn't support new architecture.

---

Current state:

can't terraform apply fails with error:

```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```

**Comment by felimartina** [comment]
Hey @n0npax,
Thanks for reporting this issue, and sorry for the big delay on getting back to you on this.

I went ahead and removed the deprecated provider in favor of `templatefile`. The solution should work fine now, let me know if you still face any issues.
