### ISSUE TITLE
I have problem with the IAM access

### ISSUE THREAD

**Issue by Madhav980** [GoogleCloudPlatform/dlp-pdf-redaction#23]
![image](https://github.com/GoogleCloudPlatform/dlp-pdf-redaction/assets/154233235/cd621fe4-2127-4d5b-bff0-023c04983876)

**Comment by felimartina** [comment]
Hi @Madhav980 , it looks like you are trying to run this from a Qwiklab Lab (CloudSkillsBoost) where you don't have enough permissions.

You should try running this on your own Google Cloud account where you do have access to IAM permissions and to create new resources.
